### ISSUE TITLE
Calendar plugin sincronizzato con Office365  , Exchange e  Google Calendar

### ISSUE THREAD

**Issue by pezzuto** [Arxivar/SamplePlugins#2]
Abbiamo installato il Calendar plugin. E' possibile renderlo sincronizzato con il calendario di Office365, Exchange e Google Calendar anzichè con una classe?

**Comment by sneeze3k** [comment]
Buongiorno,
attualmente il plugin calendario è solo un esempio di integrazione in arxivar di una nuova funzionalità tramite un plugin.
I plugin messi a disposizione su questo repository GitHub sono da intendersi a scopo dimostrativo per gli sviluppatori esterni. Grazie a questi esempi di plugin gli sviluppatori esterni possono avere una base dalla quale partire per realizzare il loro plugin per ARXivar Next. Il plugin calendario non fa eccezione ed è da intendersi come dimostrativo di una funzionalità nuova nel prodotto sviluppabile sotto forma di plugin esterno. Per questo motivo non verrà ulteriormente sviluppato.
Il codice sorgente è pubblico e può essere usato come base per qualsiasi nuova implementazione, compresa l'integrazione con calendari esterni.
